//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by chatui.rc
//
#define IDC_BTN_ADD_FRIEND              3
#define ID_BTN_EDIT_IP                  3
#define ID_BTN_ABOUT                    3
#define ID_BTN_EDIT_PASSWORD            4
#define IDC_BTN_ADD_GROUP               4
#define IDC_BTN_EDIT                    5
#define IDC_BTN_NOTIFICATION            5
#define IDD_CHAT_UI_DIALOG              102
#define IDD_messenger                   103
#define IDD_EditProfileDlg              104
#define IDD_AddFriendDlg                105
#define IDD_EditPasswordDlg             106
#define IDD_ChooseFriend                107
#define IDD_ConfirmDlg                  108
#define IDD_EmojiDlg                    109
#define IDD_ShowEmoijDlg                110
#define IDD_CreateGroupDlg              111
#define IDD_ChooseGroup                 112
#define IDI_APP                         150
#define IDI_ADD_GROUP                   186
#define IDI_ICON5                       187
#define IDI_ADD_FRIEND                  187
#define IDI_AVATAR                      188
#define IDI_ATTACH                      189
#define IDI_SEND_FILE                   189
#define IDI_TRAVEL                      190
#define IDI_NATURE                      191
#define IDI_USER_ONL                    193
#define IDI_RECENT                      194
#define IDI_USER_CHATTING               195
#define IDI_GROUP                       196
#define IDI_USER_OFF                    197
#define IDI_FOOD                        198
#define IDI_LOVE                        199
#define IDI_SEND_EMOJI                  200
#define IDI_OBJECT                      201
#define IDI_UNNOTIFICATION              202
#define IDI_NOTIFICATION                203
#define IDI_GROUP_CHATTING              204
#define IDI_SEND                        205
#define IDI_ACTIVITY                    206
#define IDI_OTHER                       207
#define IDI_ICO_GROUP_1                 213
#define IDI_ICO_GROUP_2                 214
#define IDI_ICO_GROUP_3                 215
#define IDI_ICO_GROUP_4                 216
#define IDI_ICO_GROUP_5                 217
#define IDI_ICO_GROUP_6                 218
#define IDI_ICO_GROUP_7                 219
#define IDI_ICO_GROUP_8                 220
#define IDI_ICO_GROUP_9                 221
#define IDI_ICO_GROUP_9P                222
#define IDI_LEFT                        224
#define IDI_RIGHT                       225
#define IDI_ICON3                       226
#define IDI_SWAP                        226
#define IDI_USER_1                      227
#define IDI_USER_2                      228
#define IDI_USER_3                      229
#define IDI_USER_4                      230
#define IDI_USER_5                      231
#define IDI_USER_6                      232
#define IDI_USER_7                      233
#define IDI_USER_8                      234
#define IDI_USER_9                      235
#define IDI_USER_9P                     236
#define IDI_USER                        237
#define IDI_IMAGE                       238
#define IDI_LINK                        239
#define IDI_CAMERA                      241
#define IDI_VIDEO                       242
#define IDI_ICON8                       243
#define IDI_SOUND                       244
#define IDI_ICON1                       245
#define IDI_DOC                         245
#define IDC_USERNAME                    1000
#define IDC_PASSWORD                    1001
#define IDC_BTN_LOGIN                   1002
#define IDC_BTN_REGISTER                1003
#define IDC_TITLE                       1004
#define IDC_ICON                        1009
#define IDC_LIST_FRIENDS                1010
#define IDC_MESS_CONTENT                1011
#define IDC_BTN_SEND                    1012
#define IDC_CHAT_USERNAME               1013
#define IDC_LIST_MESS                   1014
#define IDC_LIST_FRIENDS2               1015
#define IDC_LIST_GROUPS                 1015
#define IDC_FRIEND_USERNAME             1017
#define IDC_GREETING                    1018
#define IDC_BTN_SEND_ICON               1018
#define IDC_PASSss                      1019
#define IDC_CUR_PASS                    1019
#define IDC_BTN_SEND_FILE               1019
#define IDC_PASS2                       1020
#define IDC_BTN_SEND_ICON2              1020
#define IDC_BTN_CAMERA                  1020
#define IDC_PASS1                       1021
#define IDC_LIST1                       1021
#define IDC_LIST_EMOJI                  1021
#define IDC_LIST_ICON                   1021
#define IDC_LIST_FILE_TRANSFER          1021
#define IDC_BTN_SEND_ICON3              1022
#define IDC_BTN_LINK                    1022
#define IDC_BTN_SEND_ICON4              1024
#define IDC_BTN_SEND_ICON5              1025
#define IDC_BTN_VIDEO                   1025
#define ID_BTN_START_CHAT               1027
#define ID_BTN_UNFRIEND                 1028
#define IDC_CONFIRM_MESS                1029
#define ID_BTN_MODIFY_GROUP             1029
#define IDC_BTN_SEND_ICON6              1029
#define IDC_BTN_PDF                     1029
#define IDC_BTN_SOUND                   1029
#define IDC_BTN_SEND_ICON7              1030
#define IDC_BTN_WORD                    1030
#define IDC_BTN_DOC                     1030
#define IDC_BTN_SEND_ICON8              1031
#define IDC_BTN_SEND_ICON9              1033
#define IDC_BTN_IMAGE                   1033
#define IDC_GROUP_NAME                  1035
#define IDC_LIST_MEMBERS                1038
#define IDC_ARROW                       1040
#define ID_BTN_START_CHAT_GROUP         1042
#define ID_BTN_OUT_GROUP                1043
#define IDC_BTN_CREATE_GROUP            1044
#define IDC_FORM_LOGIN_MSG_HANDLER      1045
#define IDC_FORM_LOGIN_MSG_HANDLER_LOGIN_SUCESS 1046
#define IDC_FORM_LOGIN_MSG_HANDLER_LOGIN_ERROR 1047
#define IDC_FORM_LOGIN_MSG_HANDLER_REGISTER_SUCCESS 1048
#define IDC_LIST2                       1048
#define IDC_LIST_MEMBER_CHAT            1048
#define IDC_FORM_LOGIN_MSG_HANDLER_REGISTER_ERROR 1049
#define IDC_BTN_LEFT                    1049
#define IDC_FORM_CHAT_MSG_HANDLER       1050
#define IDC_BTN_SWAP                    1050
#define IDC_MFCBUTTON1                  1050
#define IDC_FORM_CHAT_MSG_HANDLER_LIST_ONLINE 1051
#define IDC_BTN_RIGHT                   1051
#define IDC_FORM_CHAT_MSG_HANDLER_HASH_CONVERSATION 1052
#define IDC_FORM_CHAT_MSG_HANDLER_RECEIVE_CONVERSATION 1053
#define IDC_FORM_CHAT_MSG_HANDLER_TRANSFER_FILE 1054
#define IDC_FORM_CHAT_MSG_HANDLER_STATUS_TRANSFER_FILE 1055
#define IDC_FORM_CHAT_MSG_HANDLER_BEGIN_TRANSFER_FILE 1056
#define IDC_FORM_CHAT_MSG_HANDLER_END_TRANSFER_FILE 1057
#define IDC_FORM_CHAT_MSG_HANDLER_SERVER_DISCONNECTED 1058

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        246
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
